
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 09 17:29:35 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_parentesis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARCIERRA = 3;
  public static final int PARABRE = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

