
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMIENZA ESTE FIN NORTE OESTE SURprograma : COMIENZA instrucciones FIN \n                | COMIENZA FIN instrucciones    : instruccion instrucciones\n                        | instruccion instruccion : NORTEinstruccion : SURinstruccion : ESTEinstruccion : OESTE'
    
_lr_action_items = {'COMIENZA':([0,],[2,]),'$end':([1,4,10,],[0,-2,-1,]),'FIN':([2,3,5,6,7,8,9,11,],[4,10,-4,-5,-6,-7,-8,-3,]),'NORTE':([2,5,6,7,8,9,],[6,6,-5,-6,-7,-8,]),'SUR':([2,5,6,7,8,9,],[7,7,-5,-6,-7,-8,]),'ESTE':([2,5,6,7,8,9,],[8,8,-5,-6,-7,-8,]),'OESTE':([2,5,6,7,8,9,],[9,9,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'instrucciones':([2,5,],[3,11,]),'instruccion':([2,5,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> COMIENZA instrucciones FIN','programa',3,'p_programa','gramatica.py',39),
  ('programa -> COMIENZA FIN','programa',2,'p_programa','gramatica.py',40),
  ('instrucciones -> instruccion instrucciones','instrucciones',2,'p_instrucciones_lista','gramatica.py',44),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_lista','gramatica.py',45),
  ('instruccion -> NORTE','instruccion',1,'p_instruccion_norte','gramatica.py',49),
  ('instruccion -> SUR','instruccion',1,'p_instruccion_sur','gramatica.py',53),
  ('instruccion -> ESTE','instruccion',1,'p_instruccion_este','gramatica.py',57),
  ('instruccion -> OESTE','instruccion',1,'p_instruccion_oeste','gramatica.py',61),
]
