
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 19 11:21:26 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_robotgrid;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACE = 17;
  public static final int RPAREN = 14;
  public static final int FCLEAR = 12;
  public static final int WHILE = 3;
  public static final int END = 6;
  public static final int ITERATE = 4;
  public static final int IF = 2;
  public static final int LBRACE = 18;
  public static final int LPAREN = 13;
  public static final int SCOLON = 16;
  public static final int PLACEWALL = 9;
  public static final int DRAWGRID = 7;
  public static final int COMMA = 15;
  public static final int TURNLEFT = 11;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int PLACEROBOT = 8;
  public static final int DIR = 20;
  public static final int error = 1;
  public static final int START = 5;
  public static final int NEQ = 19;
  public static final int MOVE = 10;
}

