
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 10 10:27:14 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_booleano;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FIN_SENTENCIA = 4;
  public static final int error = 1;
  public static final int OPERANDO = 2;
  public static final int OPERADOR = 3;
  public static final int EOF = 0;
}

