
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 10 10:10:32 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_colchita;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 8;
  public static final int PARCIERRA = 7;
  public static final int GIRO = 2;
  public static final int EOF = 0;
  public static final int COSTURA = 3;
  public static final int RETAZO_B = 5;
  public static final int RETAZO_A = 4;
  public static final int error = 1;
  public static final int PARABRE = 6;
}

