
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 15 20:43:02 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_declaracion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 2;
  public static final int error = 1;
  public static final int PUNTOCOMA = 5;
  public static final int EOF = 0;
  public static final int BOOLEANO = 4;
  public static final int ENTERO = 3;
}

