
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 08 21:56:35 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_logo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int oeste = 6;
  public static final int sur = 4;
  public static final int norte = 3;
  public static final int error = 1;
  public static final int comienza = 2;
  public static final int este = 5;
  public static final int EOF = 0;
  public static final int fin = 7;
}

