
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 18 14:15:38 ART 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 2;
  public static final int error = 1;
  public static final int PUNTOCOMA = 5;
  public static final int EOF = 0;
  public static final int BOOLEANO = 4;
  public static final int ENTERO = 3;
}

