
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 18 14:24:49 ART 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FIN_SENTENCIA = 4;
  public static final int error = 1;
  public static final int OPERANDO = 2;
  public static final int OPERADOR = 3;
  public static final int EOF = 0;
}

