
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 18 14:56:47 ART 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 7;
  public static final int COMA = 14;
  public static final int SUMA = 9;
  public static final int ENTERO = 15;
  public static final int INICIO = 2;
  public static final int COR_C = 13;
  public static final int VERTICAL = 5;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int COR_A = 12;
  public static final int error = 1;
  public static final int UBICAR = 4;
  public static final int LATERAL = 6;
  public static final int REPETIR = 11;
  public static final int RESTA = 10;
  public static final int PAR_C = 8;
}

