
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 22 18:44:47 ART 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PONER = 2;
  public static final int NEG = 15;
  public static final int RBRACE = 12;
  public static final int RPAREN = 8;
  public static final int END = 6;
  public static final int COLOR = 19;
  public static final int SACAR = 4;
  public static final int IF = 17;
  public static final int LPAREN = 7;
  public static final int HAYCOLOR = 16;
  public static final int LBRACE = 11;
  public static final int SCOLON = 10;
  public static final int COMMA = 9;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int MOVER = 3;
  public static final int DIR = 18;
  public static final int error = 1;
  public static final int TABLERO = 13;
  public static final int START = 5;
  public static final int REPEAT = 14;
}

