
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 06 21:02:08 ART 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int oeste = 6;
  public static final int sur = 4;
  public static final int EOF = 0;
  public static final int norte = 3;
  public static final int reset = 8;
  public static final int comienza = 2;
  public static final int error = 1;
  public static final int fin = 7;
  public static final int este = 5;
}

