
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 19 11:58:09 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_condicional;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int open_par = 10;
  public static final int id = 12;
  public static final int or_ = 2;
  public static final int falso = 15;
  public static final int verdadero = 14;
  public static final int EOF = 0;
  public static final int menor = 7;
  public static final int numero = 13;
  public static final int menor_igual = 9;
  public static final int no_igual = 5;
  public static final int igual_igual = 4;
  public static final int mayor_igual = 8;
  public static final int error = 1;
  public static final int and_ = 3;
  public static final int close_par = 11;
  public static final int mayor = 6;
}

